# Mathematical analysis in the context of the optimization problem

In [ ]:
import pandas as pd
import numpy as np
from collections import Counter
from collections import deque

In [ ]:
W = {1, 2, 3, 4}
B = {2, 3}
C = {4, 5, 6, 7}

print(W.intersection(B))
print(W.intersection(C))

{2, 3}
{4}


In [ ]:
print(B.issubset(W))
print(C.issubset(W))

True
False


### UNION  (C = A ⋃ B)

In [ ]:
A = {1, 2, 3, 4}
B = {2, 3, 5}

C = A.union(B)
print(C)

{1, 2, 3, 4, 5}


### INTERSECTION (C = A ∩ B)

In [ ]:
A = {1, 2, 3, 4}
B = {2, 3, 5}

C = A.intersection(B)
print(C)

{2, 3}


### DIFFERENCE (C = A \ B)

In [ ]:
A = {1, 2, 3, 4}
B = {2, 3, 5}

C = A.difference(B)
print(C)

{1, 4}


### SYMMETRIC DIFFERENCE (C = A Δ B)

In [ ]:
A = {1, 2, 3, 4}
B = {2, 3, 5}

C = A.symmetric_difference(B)
print(C)

{1, 4, 5}


### Operations on sets

In [ ]:
A = {'ID453', 'ID312', 'ID41', 'ID3', 'ID500', 'ID920', 'ID36', 'ID27'}
B = {'ID41', 'ID36', 'ID27', 'ID124', 'ID7', 'ID501', 'ID91' }

In [ ]:
# UNION
union_AB = A.union(B)
print('Union:', union_AB)
print('------')
# INTERSECTION
inter_AB = A.intersection(B)
print('Intersection:', inter_AB)
print('------')
# DIFFERENCE
diff_AB = A.difference(B)
print('Difference:', diff_AB)
print('------')
# SYMMETRIC DIFFERENCE
symm_AB = A.symmetric_difference(B)
print('Symmetric difference:', symm_AB)

Union: {'ID124', 'ID27', 'ID41', 'ID920', 'ID312', 'ID501', 'ID453', 'ID91', 'ID3', 'ID500', 'ID7', 'ID36'}
------
Intersection: {'ID36', 'ID41', 'ID27'}
------
Difference: {'ID920', 'ID312', 'ID453', 'ID3', 'ID500'}
------
Symmetric difference: {'ID124', 'ID920', 'ID312', 'ID501', 'ID91', 'ID453', 'ID3', 'ID500', 'ID7'}


### SYMPY LIBRARY

In [ ]:
from sympy import FiniteSet, Union
l1 = [1, 3, 7, 10]
l2 = [9, 7, 1]
a = FiniteSet(*l1)
b = FiniteSet(*l2)
Union(a, b)

FiniteSet(1, 3, 7, 9, 10)

In [ ]:
from sympy import ConditionSet, Eq, Symbol, Interval
x = Symbol('x')
s = ConditionSet(x, Eq(x**2-5*x,0), Interval(2,9))
s

ConditionSet(x, Eq(x**2 - 5*x, 0), Interval(2, 9))

### TASK 2.3

In [ ]:
A = {2,4,6,8,10,12}
B = {3,6,9,12}
print(A.difference(B))

{8, 2, 10, 4}


### TASK 2.4

In [ ]:
A = {2,4,6,8,10,12}
B = {3,6,9,12}
print(A.intersection(B))

{12, 6}


### TASK 2.5

In [ ]:
N = {22,23,24,25}
K = {24,25,26}
print(N.union(K))

{22, 23, 24, 25, 26}


### TASK 2.6

In [ ]:
P = {'bennet@xyz.com','darcy@abc.com','margaret@xyz.com','pa@hhh.com','marimari@xyz.com','mallika@yahoo.com','abc@xyz.com','0071235@gmail.ru'}
M = {'marimari@xyz.com','darcy@abc.com','0071235@gmail.ru','darcy@abc.com','petr44@xyz.com','katrin@ya.com'}

In [ ]:
print(len(P.intersection(M)))

3


### TASK 2.7

In [ ]:
print(len(P.union(M)))

10


### TASK 2.8

In [ ]:
print(len(P.symmetric_difference(M)))

7


### Elementary functions

In [ ]:
# Exponential function
x_arr = np.array([1, 2, 3, 4, 5, 6, 7])
y_arr = np.exp(x_arr)
print(x_arr)
print(y_arr)

[1 2 3 4 5 6 7]
[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591
  403.42879349 1096.63315843]


In [ ]:
import plotly
import plotly.express as px

fig1 = px.line(
    x= x_arr,
    y=y_arr,
    height=500,
    width=1000,
    title='f(x)=e**x'
)
fig1.show()

In [ ]:
# Logarithmic function
x_arr = np.array([1, 2, 3, 4, 5, 6, 7])
y_arr = np.emath.log(x_arr)
print(x_arr)
print(y_arr)

[1 2 3 4 5 6 7]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015]


In [ ]:
fig2 = px.line(
    x= x_arr,
    y=y_arr,
    height=500,
    width=1000,
    title='f(x)=ln x'
)
fig2.show()

In [ ]:
# Cигмоидальная функция
x_arr = np.array([1, 2, 3, 4, 5, 6, 7])
a = 1
y_arr = 1/(1 + np.exp(-a*x_arr))
print(x_arr)
print(y_arr)

[1 2 3 4 5 6 7]
[0.73105858 0.88079708 0.95257413 0.98201379 0.99330715 0.99752738
 0.99908895]


In [ ]:
fig3 = px.line(
    x= x_arr,
    y=y_arr,
    height=500,
    width=500,
    title='f(x)=ln x'
)
fig3.show()

### Function compositions

y = f(g(x))
<br>f(x) = 2x + x ** 2
<br>g(x) = ln(x)
<br>y = ln(2x + x ** 2)

### Function research

### Areas of definition and values

In [ ]:
from sympy import Symbol, S #импортируем нужные функции для обозначения переменных
from sympy.calculus.util import function_range #импортируем функцию для поиска области значения
from sympy.calculus.util import continuous_domain #импортируем функцию для поиска области определения
x = Symbol('x') #определяем нашу переменную
f = 1/x #определяем нашу функцию
continuous_domain(f, x, S.Reals) #вычисляем область определения

Union(Interval.open(-oo, 0), Interval.open(0, oo))

In [ ]:
from sympy import log
x = Symbol('x')
f = log(x)/x
continuous_domain(f, x, S.Reals)

Interval.open(0, oo)

In [ ]:
from sympy import Symbol, S, sin #импортируем нужные функции для обозначения переменных
from sympy.calculus.util import function_range #импортируем функцию для поиска области значений
x = Symbol('x')
f = sin(x)
function_range(f, x, S.Reals)

Interval(-1, 1)

In [ ]:
from sympy import Symbol, S, sin #импортируем нужные функции для обозначения переменных
from sympy.calculus.util import function_range #импортируем функцию для поиска области значений
from sympy import exp #добавляем функцию для вычисления экспоненциальной функции
x = Symbol('x')
f = (x*x-3)/(exp(x))
function_range(f, x, S.Reals)

Interval(-2*E, oo)

### Points of intersection with the abscissa and ordinate axes

In [ ]:
x = Symbol('x')
f = x*x+5*x+4
f.subs(x, 0)

4

In [ ]:
# найдём точку пересечения с осью абсцисс
from sympy import solveset, Eq
solveset(Eq(x*x+5*x+4, 0), x)

FiniteSet(-4, -1)

### TASK 4.2

In [ ]:
from sympy import Symbol, S
from sympy.calculus.util import function_range
from sympy.calculus.util import continuous_domain

In [ ]:
x = Symbol('x')
f = x**2 + 1
display(continuous_domain(f, x, S.Reals))
display(function_range(f, x, S.Reals))

Reals

Interval(1, oo)

### TASK 4.5

In [ ]:
from sympy import Symbol, S
from sympy import solveset, Eq

x = Symbol('x')
f = 6 - 2*x

display(f.subs(x, 0))
display(solveset(Eq(f, 0), x))

6

FiniteSet(3)

In [ ]:
from sympy import Symbol, S
from sympy import solveset, Eq

x = Symbol('x')
y = 2*x + 4

display(solveset(Eq(y, 0), x))
display(y.subs(x, 0))

{-2}

4

### TASK 4.6

In [ ]:
from sympy import Symbol, S
from sympy import solveset, Eq

x = Symbol('x')
f = x**2 + 2*x - 8

display(f.subs(x, 0))
display(solveset(Eq(f, 0), x))

-8

{-4, 2}

### TASK 4.7

In [ ]:
from sympy import Symbol, S
from sympy.calculus.util import function_range
from sympy.calculus.util import continuous_domain

x = Symbol('x')
f = 3 / (x**2 - 10)

display(function_range(f, x, S.Reals))
display(continuous_domain(f, x, S.Reals))

Union(Interval(-oo, -3/10), Interval.open(0, oo))

Union(Interval.open(-oo, -sqrt(10)), Interval.open(-sqrt(10), sqrt(10)), Interval.open(sqrt(10), oo))

### Derivative with Python

In [ ]:
import sympy
x = Symbol('x')
expr = x**4 + 3*x**3 + 4*x**2 + 8
expr.diff(x)

4*x**3 + 9*x**2 + 8*x

In [ ]:
import sympy
from sympy import diff, sin, exp, log, Symbol

x = Symbol('x')
expr = log(x**2 + 5*x) + exp(sin(x))
expr.diff(x)

(2*x + 5)/(x**2 + 5*x) + exp(sin(x))*cos(x)

In [ ]:
x = Symbol('x')
f = 2*x**4
display(f.diff())

8*x**3

### TASK 6.5

In [ ]:
import sympy
from sympy import diff, sin, exp, log, Symbol

x = Symbol('x')
expr = sin(x*3 + log(x)) * exp((x))
expr.diff(x)

(3 + 1/x)*exp(x)*cos(3*x + log(x)) + exp(x)*sin(3*x + log(x))


### The second derivative

In [ ]:
import sympy
from sympy import diff, sin, exp, log, Symbol

x = sympy.Symbol("x")
expr = log(x**2 + 5*x) + exp(sin(x))
expr.diff(x,2)

-exp(sin(x))*sin(x) + exp(sin(x))*cos(x)**2 + 2/(x*(x + 5)) - (2*x + 5)**2/(x**2*(x + 5)**2)

### TASK 6.6

In [ ]:
import sympy
from sympy import diff, Symbol

x = Symbol('x')
expr = (2*x +1)**2
expr.diff(x)

8*x + 4

### TASK 6.7

In [ ]:
import sympy
from sympy import Symbol, diff

x = Symbol('x')
expr = 2*x**2 +1
expr.diff(x)

4*x

### TASK 6.8

In [ ]:
import sympy
from sympy import Symbol, diff, ln, exp

x = Symbol('x')
expr = ln(5*x + 3)
expr.diff(x)

5/(5*x + 3)

### TASK 6.9

In [ ]:
import sympy
from sympy import Symbol, diff, sin, cos

x = Symbol('x')
expr = (sin(3*x))**2
expr.diff(x)

6*sin(3*x)*cos(3*x)

### TASK 6.10

In [ ]:
import sympy
from sympy import Symbol, diff, log, exp

x = Symbol('x')
expr = (2*x**3)*ln(x)
expr.diff(x)

6*x**2*log(x) + 2*x**2

In [ ]:
expr.diff(x).subs(x, 1)

2

### TASK 6.11

In [ ]:
import sympy
from sympy import Symbol, diff, sqrt

x = Symbol('x')
expr = x/(x**2 + 1)
expr.diff(x)

-2*x**2/(x**2 + 1)**2 + 1/(x**2 + 1)

In [ ]:
expr.diff(x).subs(x, 0)

1

### TASK 6.12

In [ ]:
import sympy
from sympy import Symbol, diff, sqrt

x = Symbol('x')
expr = sqrt((1 + x**2))
expr.diff(x)

x/sqrt(x**2 + 1)

### TASK 6.13

In [ ]:
import sympy
from sympy import Symbol, diff, sqrt

x = Symbol('x')
expr = x**4 + 5*x
expr.diff(x, 2)

12*x**2

In [ ]:
expr.diff(x, 2).subs(x, 5)

300

### The study of functions using derivatives

In [ ]:
import sympy
from sympy import Symbol, diff, sqrt

x = Symbol('x')
f = 1/4*x**3 - 3*x
f.diff(x, 2)

1.5*x

In [ ]:
f.diff(x,2).subs(x,4)

6.00000000000000

### TASK 7.3

In [ ]:
import sympy
from sympy import Symbol, diff, sqrt, log, exp

x = Symbol('x')
y1 = x**2
y2 = sqrt(x)
y3 = exp(x)
y4 = ln(x)

display(y1.diff(x))
display(y2.diff(x))
display(y3.diff(x))
display(y4.diff(x))
print('-----------')
display(y1.diff(x,2))
display(y2.diff(x,2))
display(y3.diff(x,2))
display(y4.diff(x,2))

2*x

1/(2*sqrt(x))

exp(x)

1/x

-----------


2

-1/(4*x**(3/2))

exp(x)

-1/x**2

### TASK 7.4

In [ ]:
import sympy
from sympy import Symbol, diff, solveset, Eq

x = Symbol('x')
f = 5*x**2 - 3*x + 100
display(f.diff(x))
display(f.diff(x, 2))

10*x - 3

10

In [ ]:
solveset(Eq(f.diff(x), 0), x)

FiniteSet(3/10)

### TASK 7.5

In [ ]:
import sympy
from sympy import Symbol, diff, solveset, Eq

x = Symbol('x')
f = x**3 - 6*x
display(f.diff(x))
display(f.diff(x, 2))

3*x**2 - 6

6*x

In [ ]:
display(solveset(Eq(f.diff(x),0), x))
display(solveset(Eq(f.diff(x, 2),0), x))

FiniteSet(sqrt(2), -sqrt(2))

FiniteSet(0)

### TASK 7.6

In [ ]:
import sympy
from sympy import Symbol, diff, sqrt, exp, log

x = Symbol('x')

y1 = x**2
y2 = x**3
y3 = sqrt(x)
y4 = exp(x)
y5 = -exp(x)
y6 = ln(x)

display(y1.diff(x, 2))
display(y2.diff(x, 2))
display(y3.diff(x, 2))
display(y4.diff(x, 2))
display(y5.diff(x, 2))
display(y6.diff(x, 2))

2

6*x

-1/(4*x**(3/2))

exp(x)

-exp(x)

-1/x**2

### TASK 7.8

In [ ]:
import sympy
from sympy import Symbol, diff, sqrt, exp, log

x = Symbol('x')
y = 1/(1 + exp(x))
y.diff(x, 2)

(-1 + 2*exp(x)/(exp(x) + 1))*exp(x)/(exp(x) + 1)**2

### TASK 7.9

In [ ]:
import sympy
from sympy import Symbol, diff, sqrt, exp, log

x = Symbol('x')
y = x**2 + ln(x)
y.diff(x, 2)

2 - 1/x**2

## Eigenvectors and numbers

In [ ]:
# TASK 3.2

import numpy as np
A = np.array([
    [-7, 6],
    [-12, 11]
])

λ1 = -1
λ2 = 5

v1 = np.array([1,2])
v2 = np.array([1,1])

print(A @ v1)
print(A @ v2)
print('------')
print(v1 * λ1)
print(v2 * λ2)
print('-----')
print(v1 * λ2)
print(v2 * λ1)

[ 5 10]
[-1 -1]
------
[-1 -2]
[5 5]
-----
[ 5 10]
[-1 -1]


In [ ]:
# TASK 3.3

A = np.array([
    [5, 1],
    [1, 5]
])

λ1 = 6
λ2 = 4

v1 = np.array([1,1])
v2 = np.array([-1,1])
v3 = np.array([0,2])
v4 = np.array([4,4])

print(A @ v1)
print(A @ v2)
print(A @ v3)
print(A @ v4)
print('------')
print(v1 * λ1)
print(v2 * λ1)
print(v3 * λ1)
print(v4 * λ1)
print('------')
print(v1 * λ2)
print(v2 * λ2)
print(v3 * λ2)
print(v4 * λ2)

[6 6]
[-4  4]
[ 2 10]
[24 24]
------
[6 6]
[-6  6]
[ 0 12]
[24 24]
------
[4 4]
[-4  4]
[0 8]
[16 16]


In [ ]:
# TASK 3.5

v = np.array([1, 1])
u = np.array([1, -1])

print(v @ u)

0
