In [ ]:
import numpy as np

In [ ]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [ ]:
A

array([[ 8, 11, 11],
       [ 8,  5,  5],
       [ 7, 11,  6]])

In [ ]:
B

array([[-1, -2,  1],
       [ 3,  0, -2],
       [ 1,  1,  0]])

In [ ]:
# Поэлементное умножение
A*B

array([[ -8, -22,  11],
       [ 24,   0, -10],
       [  7,  11,   0]])

In [ ]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 36  -5 -14]
 [ 12 -11  -2]
 [ 32  -8 -15]]


In [ ]:
# Матричное умножение
np.dot(A,B)

array([[ 36,  -5, -14],
       [ 12, -11,  -2],
       [ 32,  -8, -15]])

In [ ]:
# Матричное умножение
A@B

array([[ 36,  -5, -14],
       [ 12, -11,  -2],
       [ 32,  -8, -15]])

In [ ]:
# Порядок умножения AB != BA
B@A

array([[-17, -10, -15],
       [ 10,  11,  21],
       [ 16,  16,  16]])

In [ ]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[11  7 11  8  7]
 [ 6  9  7 10  5]
 [11 11  8 11 10]]
B:
 [[ 1  1]
 [ 2  1]
 [ 2 -1]
 [ 1  0]
 [-1  2]]


In [ ]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[48, 21],
       [43, 18],
       [50, 34]])

In [ ]:
# Умножение прямоугольных матриц возможно не в любом порядке
# B@A

In [ ]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [ ]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 1 -4  1  2]
 [ 1  0 -3  2]
 [ 0 -2  3 -2]
 [ 2 -2  0  3]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 1 -8  0 -2]
 [ 1  0  0 -2]
 [ 0 -4  0  2]
 [ 2 -4  0 -3]]
DA:
 [[ 1 -4  1  2]
 [ 2  0 -6  4]
 [ 0  0  0  0]
 [-2  2  0 -3]]


In [ ]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [ ]:
b@A

ValueError: ignored

In [2]:
import numpy as np

In [3]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [4]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [5]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [6]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [ ]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

### TASK 7.1

In [ ]:
A = np.array([
    [5, -1, 3, 1, 2],
    [-2, 8, 5, -1, 1]
])

x = np.array([1, 2, 3, 4, 5])

Ax = A@x
print(Ax)

### TASK 7.2

In [ ]:
A = np.array([
    [1,9,8,5], 
    [3,6,3,2], 
    [3,3,3,3], 
    [0,2,5,9], 
    [4,4,1,2]
])

B = np.array([
    [1,-1,0,1,1], 
    [-2,0,2,-1,1]
])

BA = B@A
print(BA)
print(BA[0,3]) 

### TASK 7.3

In [ ]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

A = np.array([x, y, z])
print(A)

print('------')

G = A.transpose()@A
print(G)

### TASK 7.4

In [ ]:
import pandas as pd

In [ ]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Count_DF

In [ ]:
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Price_DF

In [ ]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [ ]:
net = Count_DF.values * Price_DF.values
print(net)

In [ ]:
income = net * com
print(income)

In [ ]:
income_salon = sum(income.transpose())
print(income_salon)

### TASK 7.5

In [ ]:
total_income = sum(net.transpose())
income_special = total_income - income_salon

print(income_special)