# MATH. Vectors.

In [ ]:
import pandas as pd
import numpy as np
from collections import Counter
from collections import deque

In [ ]:
s = np.array([33,65,50,45])
s

array([33, 65, 50, 45])

In [ ]:
print(s[2])
print(len(s))

50
4


### TASK 2.1

In [ ]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [ ]:
print(t[5])
print(np.where(t==min(t)))
print(t[1])
print(np.where(t==max(t)))

28
(array([0]),)
14
(array([6, 7]),)


In [ ]:
v = np.where(t==31)
v

(array([6, 7]),)

### TASK 2.2

In [ ]:
vec1 = np.array([3, -5])
vec1_len = np.linalg.norm(vec1)

print(vec1_len)

5.830951894845301


### Sum

In [ ]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

c = a + b
d = a - b
print(c)
print(d)

[15 23 14  8]
[ 5 -7 -4 -6]


### Multiplying a vector by a scalar

In [ ]:
vec1 = np.array([120, 45, 68])
w = 0.2
vec2 = vec1 * w

print(sum(vec2))

46.6


### TASK 2.3

In [ ]:
#x = np.array([1, 2, 3**0.5])
#y = np.array([-1, -2])
#с = x + y
#print(c)

### TASK 2.4

In [ ]:
x = np.array([5, 2])
y = np.array([-5, -11])

c = x + y
d = x - y
print(c)
print(d)

[ 0 -9]
[10 13]


### TASK 2.5

In [ ]:
h_rub = np.array([120, 150, 190])
w_rub = np.array([130, 130, 130])
wm_euro = np.array([2, 3, 2.5])
euro_rub = 72

wm_rub = wm_euro * euro_rub
print(wm_rub)

sum_rub = h_rub + w_rub + wm_rub
print(sum_rub)

[144. 216. 180.]
[394. 496. 500.]


### TASK 2.6

In [ ]:
a = np.array([4, 6])
b = np.array([-1, -2])

c = a + b
norm_c = np.linalg.norm(c)
print(norm_c)

5.0


### Linear combinations

In [ ]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
o = np.array([0, 12, 7])

p_rate = 500
v_rate = 100
o_rate = 0

p_profit = p * p_rate
print(p_profit)
v_profit = v * v_rate
print(v_profit)
o_profit = o * o_rate
print(o_profit)

total_profit = p_profit + v_profit + o_profit
print(total_profit)

[1000 2000 2500]
[ 800 1000  200]
[0 0 0]
[1800 3000 2700]


### Null linear combination

In [ ]:
v1 = np.array([1, 1, 0])
v2 = np.array([1, 2, 0])
v3 = np.array([3, 4, 0])

w1 = 2
w2 = 1
w3 = -1

print(v1*w1)
print(v2*w2)
print(v3*w3)

print('____________________')

vs = v1*w1 + v2*w2 + v3*w3
print(vs)

[2 2 0]
[1 2 0]
[-3 -4  0]
____________________
[0 0 0]


### Linear (not)dependence

In [ ]:
# Linear dependence
a = np.array([1, 1, 0])
b = np.array([1, 2, 0])
x = np.array([3, 4, 0])

print(f'{2*a + b}')
print(x == (2*a + b))

[3 4 0]
[ True  True  True]


In [ ]:
# Nontrivial linear combination
a = np.array([1, 1, 0])
b = np.array([1, 2, 0])
x = np.array([3, 4, 0])

vec_null = a*2 + b*1 + x*(-1)
print(vec_null)

[0 0 0]


In [ ]:
# Linear independence
a = np.array([1, 1, 0])
b = np.array([1, 2, 0])
x = np.array([3, 4, 1])

print(2*a + b)

[3 4 0]


### TASK 2.7

In [ ]:
x = np.array([4, 5])
y = np.array([2, 1])
u = np.array([1, 0])

vec_sum = x*2 + y*(-3) + u*5
print(vec_sum)

[7 7]


### TASK 2.8

In [ ]:
created_qtn = np.array([3, 4, 5, 9])
sold_qtn = np.array([1, 5, 3, 6])

cost_price = 200
sale_price = 400

margin = created_qtn*cost_price*(-1) + sold_qtn*sale_price
print(margin)

[-200 1200  200  600]


### TASK 2.9

In [ ]:
x1 = np.array([-1, -2])
y1 = np.array([1, 2])
print(x1 + y1)
print('---------------')
x2 = np.array([-3, -2])
y2 = np.array([1, 1]) 
u2 = np.array([4, 3]) 
print(x2*(-1) + y2*1)
print((x2*(-1) + y2*1) == u2)
print('---------------')
x3 = np.array([-3, -2])
y3 = np.array([1, 1]) 
print(x3 + y3*3)

[0 0]
---------------
[4 3]
[ True  True]
---------------
[0 1]


### Scalar Product of vectors

In [ ]:
# Scalar Product
v1 = np.array([65, 70, 120, 30])
v2 = np.array([40, 40, 20, 80])

s1 = sum(v1 * v2)
s2 = np.dot(v1, v2)
print(s1)
print(s2)

10200
10200


In [ ]:
# Vector lenght
a = np.array([3, 4])
b = np.array([-1, 1, 2, 0])

lenght_a = np.dot(a,a)**0.5
lenght_a2 = np.linalg.norm(a)
lenght_b = np.dot(b,b)**0.5
lenght_b2 = np.linalg.norm(b)

print(lenght_a)
print(lenght_a2)
print(lenght_b)
print(lenght_b2)

5.0
5.0
2.449489742783178
2.449489742783178


In [ ]:
# Properties of the Scalar Product
a = np.array([2, 3])
b = np.array([-9, 6])

s = np.dot(a, b)
print(s)

0


### TASK 2.11

In [ ]:
x = np.array([4, 5, -1])
y = np.array([2, 0, 1])

s = np.dot(x, y)
print(s)

7


### TASK 2.13

In [ ]:
x1 = np.array([4, 2, -1])
y1 = np.array([2, 0, 1])

x2 = np.array([4, 5, -1])
y2 = np.array([0, 0, 0])

x3 = np.array([4, -1])
y3 = np.array([-1, 4])

x4 = np.array([4, -1])
y4 = np.array([1, 4])

c1 = np.dot(x1, y1)
c2 = np.dot(x2, y2)
c3 = np.dot(x3, y3)
c4 = np.dot(x4, y4)

print(c1, c2, c3, c4)

7 0 -8 0


### Vector recording of a linear regression model

w = (w0, w1, w2, w3)
<br>x = (1, x1, x2, x3)
<br>y_pred = w * x

Решается задача предсказания индивидуальных медицинских расходов (в долларах) на основе следующих признаков:
<br>x1 - age — возраст основного бенефициара;
<br>x2 - sex — пол страхового подрядчика (1 — мужчина, 0 — женщина);
<br>x3 - bmi — индекс массы тела (кгм), в идеале — от 18.5 до 24.9;
<br>x4 - children — количество детей, охваченных медицинской страховкой;
<br>x5 - smoker — является ли человек курящим (1 — да, 0 — нет).
<br> w = np.array([w0,w1,w2,w3,w4,w5])

In [ ]:
w = np.array([-6118, 220.8, 0, 332.2, 563, 0])

Чему будет равен прогноз медицинских расходов  для 45-летнего курящего мужчины с двумя детьми и индексом массы тела, равным 25.175?

In [ ]:
# Составим вектор x
x = np.array([1, 45, 1, 25.175, 2, 1])

# Вычисляем скаляроное произведение
y_pred = np.dot(w, x)
print(y_pred)

13307.135


### Task 1

In [ ]:
s_total = np.array([33, 42, 33, 65])
s_living = np.array([24, 32, 20, 48])
rent = np.array([39, 50, 38, 77])

w1 = 1
w2 = 0.25

p = w1 * s_total + w2 * s_living
print(p)

[39. 50. 38. 77.]


In [ ]:
s_total2 = np.array([50])
s_living2 = np.array([40])

w1 = 1
w2 = 0.25

p2 = w1 * s_total2 + w2 * s_living2
print(p2)

[60.]


### Task 2

In [ ]:
s_total = np.array([33, 42, 33, 65])
s_living = np.array([24, 32, 20, 48])
p_real = np.array([40, 48.46, 39, 77])

w1 = 1
w2 = 0.25

p = w1 * s_total + w2 * s_living
print(p_real)
print(p)

[40.   48.46 39.   77.  ]
[39. 50. 38. 77.]


In [ ]:
n = p_real - p
print(p)
print(n)

[39. 50. 38. 77.]
[ 1.   -1.54  1.    0.  ]


In [ ]:
pn = 39*1 + 50*(-1.54) + 38*1 + 77*0
print(pn)

0.0


### Task 3

In [ ]:
s_total = np.array([33, 42, 33, 65])
s_living = np.array([24, 32, 20, 48])
s_noliving = np.array([9, 10, 13, 17])
p_real = np.array([40, 48.46, 38, 77])

s_noliving_diff = s_total - s_living
print(s_noliving_diff)
print(s_noliving == s_noliving_diff)

[ 9 10 13 17]
[ True  True  True  True]


# MATH. Matrix.

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, -5, 3],
              [2, 2, 1],
              [0, 3, 1],
              [2, 4, 12]])
print(A)
print('----------')
print(A.shape)

[[ 1 -5  3]
 [ 2  2  1]
 [ 0  3  1]
 [ 2  4 12]]
----------
(4, 3)


In [ ]:
print(f'a23: {A[1,2]}')
print(f'a32: {A[2,1]}')
print(f'a33: {A[2,2]}')

a23: 1
a32: 3
a33: 1


### TASK 4.1

In [ ]:
A = np.array([
    [1,-1,2,4,0],
    [8,2,0,5,3],
    [0,1,2,1,2]
])

print(A.shape)
print(A[1,3])

(3, 5)
5


### Matrix Addition

In [ ]:
A = np.array([
    [1, -5],
    [2, 2],
    [0, 3]
])

B = np.array([
    [3, -1],
    [2, 6],
    [4, 0]
])

C = A + B
print(C)

[[ 4 -6]
 [ 4  8]
 [ 4  3]]


### Multiplying a matrix by a scalar

In [ ]:
B = np.array([
    [3, -1],
    [2, 6],
    [4, 0]
])

w = 5

C = B * w
print(C)

[[15 -5]
 [10 30]
 [20  0]]


### Matrix transposition

In [ ]:
A = np.array([
    [1, -5],
    [2, 2],
    [0, 3]
])

A_t = A.transpose() 
A_t_t = A_t.transpose()
print(A)
print('------------')
print(A_t)
print('------------')
print(A_t_t)
print('------------')
print(A.T)

[[ 1 -5]
 [ 2  2]
 [ 0  3]]
------------
[[ 1  2  0]
 [-5  2  3]]
------------
[[ 1 -5]
 [ 2  2]
 [ 0  3]]
------------
[[ 1  2  0]
 [-5  2  3]]


In [ ]:
v = np.array([
    [7],
    [5],
    [1]
])

v_t = v.transpose()
print(v)
print('---------')
print(v_t)

[[7]
 [5]
 [1]]
---------
[[7 5 1]]


In [ ]:
A = np.array([
    [1, 0, 0],
    [0, 5, 0],
    [0, 0, 7]
])

S = np.array([
    [1, 2, 4],
    [2, 5, -1],
    [4, -1, 7]
])

A_t = A.transpose()
S_t = S.transpose()
print(A_t)
print('--------')
print(S_t)

[[1 0 0]
 [0 5 0]
 [0 0 7]]
--------
[[ 1  2  4]
 [ 2  5 -1]
 [ 4 -1  7]]


### Image processing

In [ ]:
R = np.array([
    [200, 245, 200, 200, 245, 200],
    [200, 200, 200, 200, 200, 200],
    [200, 245, 200, 200, 245, 200],
    [200, 200, 245, 245, 200, 200]
])

G = np.array([
    [150, 195, 150, 150, 195, 150],
    [150, 150, 150, 150, 150, 150],
    [150, 195, 150, 150, 195, 150],
    [150, 150, 195, 195, 150, 150]
])

B = np.array([
    [60, 105, 60, 60, 105, 60],
    [60, 60, 60, 60, 60, 60],
    [60, 105, 60, 60, 105, 60],
    [60, 60, 105, 105, 60, 60]
])

M = (np.ones(24)*255).reshape((4,6))

In [ ]:
# Inversion of colors

R_new = M - R
G_new = M - G
B_new = M - B
print(R_new)
print('----------')
print(G_new)
print('----------')
print(B_new)

[[55. 10. 55. 55. 10. 55.]
 [55. 55. 55. 55. 55. 55.]
 [55. 10. 55. 55. 10. 55.]
 [55. 55. 10. 10. 55. 55.]]
----------
[[105.  60. 105. 105.  60. 105.]
 [105. 105. 105. 105. 105. 105.]
 [105.  60. 105. 105.  60. 105.]
 [105. 105.  60.  60. 105. 105.]]
----------
[[195. 150. 195. 195. 150. 195.]
 [195. 195. 195. 195. 195. 195.]
 [195. 150. 195. 195. 150. 195.]
 [195. 195. 150. 150. 195. 195.]]


In [ ]:
# Reducing brightness
R_new2 = 0.8 * R
G_new2 = 0.8 * G
B_new2 = 0.8 * B

print(R_new2)
print('--------')
print(G_new2)
print('--------')
print(B_new2)

[[160. 196. 160. 160. 196. 160.]
 [160. 160. 160. 160. 160. 160.]
 [160. 196. 160. 160. 196. 160.]
 [160. 160. 196. 196. 160. 160.]]
--------
[[120. 156. 120. 120. 156. 120.]
 [120. 120. 120. 120. 120. 120.]
 [120. 156. 120. 120. 156. 120.]
 [120. 120. 156. 156. 120. 120.]]
--------
[[48. 84. 48. 48. 84. 48.]
 [48. 48. 48. 48. 48. 48.]
 [48. 84. 48. 48. 84. 48.]
 [48. 48. 84. 84. 48. 48.]]


In [ ]:
# Rotation

R_new3 = R.transpose()
G_new3 = G.transpose()
B_new3 = B.transpose()

print(R_new3)
print('--------')
print(G_new3)
print('--------')
print(B_new3)

[[200 200 200 200]
 [245 200 245 200]
 [200 200 200 245]
 [200 200 200 245]
 [245 200 245 200]
 [200 200 200 200]]
--------
[[150 150 150 150]
 [195 150 195 150]
 [150 150 150 195]
 [150 150 150 195]
 [195 150 195 150]
 [150 150 150 150]]
--------
[[ 60  60  60  60]
 [105  60 105  60]
 [ 60  60  60 105]
 [ 60  60  60 105]
 [105  60 105  60]
 [ 60  60  60  60]]


### TASK 4.4

In [ ]:
A = np.array([
    [1, 1],
    [5, 7]
])

B = np.array([
    [6, 1],
    [-5, 5]
])

C = A + B
print(C)

[[ 7  2]
 [ 0 12]]


### TASK 4.5

In [ ]:
A = np.array([
    [1, 3],
    [2, 9]
])

a = 3

C = A * a
print(C)

[[ 3  9]
 [ 6 27]]


### TASK 4.6

In [ ]:
R = np.array([
    [1, 5, 4],
    [0, 1, 0]
])

R_t = R.transpose()
print( R_t)

[[1 0]
 [5 1]
 [4 0]]


# Matrix multiplication

In [ ]:
import numpy as np

In [ ]:
A = np.array([
    [1, -5],
    [2, 2],
    [0, 3]
])

B = np.array([
    [3, 1, 0, 4],
    [-1, 0, 2, 1]
])

C = np.array([
    [np.dot(A[0], B[:,0]), np.dot(A[0], B[:,1]), np.dot(A[0], B[:,2]), np.dot(A[0], B[:,3])],
    [np.dot(A[1], B[:,0]), np.dot(A[1], B[:,1]), np.dot(A[1], B[:,2]), np.dot(A[1], B[:,3])],
    [np.dot(A[2], B[:,0]), np.dot(A[2], B[:,1]), np.dot(A[2], B[:,2]), np.dot(A[2], B[:,3])]
])

print(C)

[[  8   1 -10  -1]
 [  4   2   4  10]
 [ -3   0   6   3]]


In [ ]:
A = np.array([
    [1, -5],
    [2, 2],
    [0, 3]
])

B = np.array([
    [3, 1, 0],
    [-1, 0, 2]
])

print(A.shape)
print(B.shape)

(3, 2)
(2, 3)


In [ ]:
# C1 = A * B
C1 = np.array([
    [np.dot(A[0], B[:,0]), np.dot(A[0], B[:,1]), np.dot(A[0], B[:,2])],
    [np.dot(A[1], B[:,0]), np.dot(A[1], B[:,1]), np.dot(A[1], B[:,2])],
    [np.dot(A[2], B[:,0]), np.dot(A[2], B[:,1]), np.dot(A[2], B[:,2])]
])

print(C1)

[[  8   1 -10]
 [  4   2   4]
 [ -3   0   6]]


In [ ]:
# C1 = B * A
C2 = np.array([
    [np.dot(B[0], A[:,0]), np.dot(B[0], A[:,1])],
    [np.dot(B[1], A[:,0]), np.dot(B[1], A[:,1])]
])

print(C2)

[[  5 -13]
 [ -1  11]]


### Matrix multiplication in Python

In [ ]:
A = np.matrix([
    [1, -5],
    [2, 2],
    [0, 3]
])


B = np.matrix([
    [3, 1, 0],
    [-1, 0, 2]
])

C1 = np.dot(A, B)
C2 = np.dot(B, A)
print(C1)
print('------------')
print(C2)

[[  8   1 -10]
 [  4   2   4]
 [ -3   0   6]]
------------
[[  5 -13]
 [ -1  11]]


In [ ]:
A = np.matrix([
    [2, 3],
    [1, 3]
])

B = np.matrix([
    [4, 1],
    [1, 0]
])

C1 = np.dot(A, B)
print(C1)
print('----------')
C2 = np.dot(B, A)
print(C2)

[[11  2]
 [ 7  1]]
----------
[[ 9 15]
 [ 2  3]]


### Multiplying a matrix by a vector

In [ ]:
A = np.matrix([
    [1, 2, 3],
    [4, 1, 1],
    [0, 2, 1]
])

b = np.array([
    [1],
    [2], 
    [-1]
])

Ab = np.dot(A, b)
print(Ab)

[[2]
 [5]
 [3]]


In [ ]:
bA = np.dot(b, A)
print(bA)

ValueError: ignored

In [ ]:
A = np.matrix([
    [1, 2, 3],
    [4, 1, 1],
    [0, 2, 1]
])

b = np.array([
    [1],
    [2], 
    [-1]
])

b_t = b.transpose()
b_tA = np.dot(b_t, A)
print(b_tA)

[[9 2 4]]


In [ ]:
Ab_t = np.dot(A, b_t)
print(Ab_t)

ValueError: ignored

### Tensor product of vectors

In [ ]:
v = np.matrix([1, 2, 3])
u = np.matrix([4, 5, 6])

# Tensor product 
v = v.transpose()
tenzor = np.dot(v, u)
print(f'Tensor product {tenzor}')

Tensor product [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
v = np.array([1, 2, 3])
u = np.array([4, 5, 6])

# Scalar product 
u = u.transpose()
scalar = np.dot(v, u)
print(f'Scalar product {scalar}')

Scalar product 32


### TASK 6.3

In [ ]:
A = np.matrix([
    [1, -1, 2, 4, 0],
    [8, 2, 0, 5, 3],
    [0, 1, 2, 1, 2]
])

B = np.matrix([
    [1, 0, 1, 0],
    [0, 0, 2, -1],
    [1, 0, 1, 1],
    [0, 1, 1, 1],
    [1, 1, 0, -1]
])

C = np.dot(A, B)
print(C)
print('-------')
print(C[0,1])
print('-------')
print(C[2,3])

[[ 3  4  5  7]
 [11  8 17  0]
 [ 4  3  5  0]]
-------
4
-------
0


In [ ]:
a = np.matrix([1, 3])
b = np.matrix([-3, 1])

a = a.transpose()
ab = np.dot(a, b)
print(ab)

[[-3  1]
 [-9  3]]


### Geometric interpretation

In [ ]:
L = np.matrix([
    [1, 0],
    [-2, 1]
])

v1 = np.matrix([3, 4]).transpose()
v2 = np.matrix([-2, 1]).transpose()

u1 = np.dot(L, v1)
u2 = np.dot(L, v2)

print(u1)
print('-------')
print(u2)

[[ 3]
 [-2]]
-------
[[-2]
 [ 5]]


### Compression/Stretching Operator

In [ ]:
L = np.matrix([
    [2/3, 0],
    [0, 3/2]
])

v = np.matrix([3, 4]).transpose()

u = np.dot(L, v)
print(u)

[[2.]
 [6.]]


### Rotation Operator

In [ ]:
L = np.matrix([
    [0, -1],
    [1, 0]
])

v = np.matrix([3, 4])
v = v.transpose()

u = np.dot(L, v)
print(u)

[[-4]
 [ 3]]


In [ ]:
v = np.array([3, 4])
u = np.array([-4, 3])
scalar = np.dot(u, v)

print(scalar)

0


### Multiplication by a null matrix

In [ ]:
A = np.matrix([
    [1, 2, 3],
    [4, 1, 1],
    [0, 2, 1]
])

N = np.zeros((3,3))

AN = np.dot(A, N)
print(AN)
print(AN == np.dot(N, A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Multiplication by a unit matrix

In [ ]:
A = np.matrix([
    [1, 2, 3],
    [4, 1, 1],
    [0, 2, 1]
])

E = np.matrix([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

AE = np.dot(A, E)
print(AE)
print(AE == np.dot(E, A))

[[1 2 3]
 [4 1 1]
 [0 2 1]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Multiplication by a spherical matrix

In [ ]:
A = np.matrix([
    [1, 2, 3],
    [4, 1, 1],
    [0, 2, 1]
])

B = np.matrix([
    [2, 0, 0],
    [0, 2, 0],
    [0, 0, 2]
])

AB = np.dot(A, B)
print(AB)
print(AB == np.dot(B, A))

[[2 4 6]
 [8 2 2]
 [0 4 2]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Multiplication by a diagonal matrix

In [ ]:
A = np.matrix([
    [1, 2, 3],
    [4, 1, 1],
    [0, 2, 1]
])

B = np.matrix([
    [1, 0, 0],
    [0, 2, 0],
    [0, 0, 3]
])

AB = np.dot(A, B)
print(AB)
print('-------')
BA = np.dot(B, A)
print(BA)

[[1 4 9]
 [4 2 3]
 [0 4 3]]
-------
[[1 2 3]
 [8 2 2]
 [0 6 3]]


In [ ]:
A = np.matrix([
    [1, 0, 0],
    [0, 2, 0],
    [0, 0, 3]
])

B = np.matrix([
    [4, 0, 0],
    [0, 5, 0],
    [0, 0, 6]
])

AB = np.dot(A, B)
print(AB)
print(AB == np.dot(B, A))

[[ 4  0  0]
 [ 0 10  0]
 [ 0  0 18]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### TASK 6.7

In [ ]:
A = np.matrix([
    [2, 0],
    [0, 2]
])

B = np.matrix([
    [1, 1],
    [4, 5]
])

AB = np.dot(A, B)
print(AB)

[[ 2  2]
 [ 8 10]]


### Matrix multiplication and transposition

In [ ]:
A = np.matrix([
    [1, 2],
    [3, 1]
])

B = np.matrix([
    [2, 6],
    [1, 1]
])

AB_t = np.dot(A, B).transpose()

A_t = A.transpose()
B_t = B.transpose()
B_t_A_t = np.dot(B_t, A_t)

print(AB_t)
print('------')
print(B_t_A_t)

[[ 4  7]
 [ 8 19]]
------
[[ 4  7]
 [ 8 19]]


### The Gram Matrix

In [ ]:
X = np.matrix([
    [1, 1],
    [1, 2],
    [0, -1]
])

X_t = X.transpose()

X_X_t = np.dot(X, X_t)
X_t_X = np.dot(X_t, X)
print(X_X_t)
print('---------')
print(X_t_X)

[[ 2  3 -1]
 [ 3  5 -2]
 [-1 -2  1]]
---------
[[2 3]
 [3 6]]


### TASK 6.9

In [ ]:
A = np.matrix([
    [1, 2, 1],
    [1, -1, 2]
])

A_t = A.transpose()

G = A_t @ A
print(G)

[[2 1 3]
 [1 5 0]
 [3 0 5]]


### Inverse matrix

In [ ]:
import numpy as np
A = np.array([
    [1, 2],
    [3, 7]
])

A_inv = np.array([
    [7, -2],
    [-3, 1]
])

AA_inv = A @ A_inv
print(AA_inv)

print('-----------')

A_invA = A_inv @ A
print(A_invA)

[[1 0]
 [0 1]]
-----------
[[1 0]
 [0 1]]


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [4, -2],
    [-3, 1]
])

E_false = A @ B
print(E_false)

print('-------')

A_inv = -1/2 * B
E_true = A @ A_inv
print(E_true) 

[[-2  0]
 [ 0 -2]]
-------
[[1. 0.]
 [0. 1.]]


In [ ]:
A = np.array([
    [5, 7],
    [3, -2]
])

print(A[0,0]*A[1,1])

-10


In [ ]:
A = np.array([
    [5, 7],
    [3, -2]
])

A_mod = np.array([
    [-2, -7],
    [-3, 5]
])

A_inv = (1 / (A[0,0]*A[1,1] - A[0,1]*A[1,0])) * A_mod
print(A_inv)

[[ 0.06451613  0.22580645]
 [ 0.09677419 -0.16129032]]


In [ ]:
E = A @ A_inv
print(np.around(E))

[[ 1. -0.]
 [ 0.  1.]]


### Inverse matrix with Python

In [ ]:
A = np.matrix('1,2,3; 4,5,6; 7,8,10')

A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


### TASK 8.1

In [ ]:
A = np.array([
    [1, 2],
    [2, 4]
])
A_mod = np.array([
    [4, -2],
    [-2, 1]
])

A_inv1 = (1/(A[0,0]*A[1,1] - A[0,1]*A[1,0])) * A_mod
print(np.around(A_inv1))

print('-----')

#A_inv2 = np.linalg.inv(A)
#print(A_inv2)

[[ inf -inf]
 [-inf  inf]]
-----


<ipython-input-164-a0583a1ab87d>:10: RuntimeWarning: divide by zero encountered in long_scalars
  A_inv1 = (1/(A[0,0]*A[1,1] - A[0,1]*A[1,0])) * A_mod


### TASK 8.2

In [ ]:
A = np.array([
    [1, 2],
    [2, 5]
])

A_inv = np.linalg.inv(A)
print(np.around(A_inv))

[[ 5. -2.]
 [-2.  1.]]


### TASK 8.3

In [ ]:
A = np.array([
    [1, 2],
    [2, 5]
])

A_inv = np.linalg.inv(A)
print(np.around(A_inv))

[[ 5. -2.]
 [-2.  1.]]


### Calculation of the determinant

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

det_A = np.linalg.det(A)
print(np.around(det_A))

-2.0


In [ ]:
A = np.matrix('1,2,3; 4,5,6; 7,8,10')
print(A)

print('------')

print(np.linalg.det(A))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
------
-2.9999999999999996


### Properties of the determinant

In [ ]:
E = np.array([
    [1, 0],
    [0, 1]
])
print(np.linalg.det(E))

1.0


In [ ]:
D = np.array([
    [5, 0],
    [0, 8]
])

print(np.around(np.linalg.det(D)))

40.0


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

coeff = 3
A_3 = coeff * A
print(A_3)

print('-------')

det_A = np.linalg.det(A)
print(np.around(det_A))

print('-------')

det_A_3 = np.linalg.det(A_3)
print(np.around(det_A_3))

print('--------')

print(np.around(coeff**A.shape[0] * det_A))

[[ 3  6]
 [ 9 12]]
-------
-2.0
-------
-18.0
--------
-18.0


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

A_t = A.T

det_A = np.linalg.det(A)
det_A_t = np.linalg.det(A_t)

print(np.around(det_A))
print('------')
print(np.around(det_A_t))

-2.0
------
-2.0


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [-1, 1],
    [3, 0]
])

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_AB = det_A * det_B
print(np.around(det_AB))

print('-----')

AB = A @ B
det_AB2 = np.linalg.det(AB)
print(np.around(det_AB2))

6.0
-----
6.0


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

inv_A = np.linalg.inv(A)

det_A = np.linalg.det(A)
det_inv_A = np.linalg.det(inv_A)

print(np.around(det_A, 1))
print('------')
print(np.around(det_inv_A, 1))
print('------')
print(np.around(det_A * det_inv_A))

-2.0
------
-0.5
------
1.0


### Degeneracy of matrices

In [ ]:
A = np.array([
    [1, 1],
    [0, 0]
])

det_A = np.linalg.det(A)
print(det_A)

0.0


### TASK 8.6

In [ ]:
A = np.array([
    [1, 2],
    [1, 1]
])

B = np.array([
    [5, -2],
    [-1, 4]
])

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
A_B = A + B
det_A_B = np.linalg.det(A_B)

print(np.around(det_A,1))
print('------')
print(np.around(det_B,1))
print('------')
print(np.around(det_A_B, 1))

-1.0
------
18.0
------
30.0


### TASK 8.8

In [ ]:
A = np.array([
    [2, 0, 0],
    [0, 1, 4],
    [0, 0, 4]
])

inv_A = np.linalg.inv(A)
print(np.linalg.det(A))
print(np.linalg.det(inv_A))

7.999999999999998
0.12500000000000003


### Linear dependence of vectors. The rank of the matrix. Basis



In [ ]:
y = 280
x = 2*y - 210

print(y)
print('-----')
print(x)

280
-----
350


In [ ]:
z = - 0.5
x = z
y = -2*z
print(z)
print(x)
print(y)

-0.5
-0.5
1.0


### TASK 9.2

In [ ]:
y = -2
print((-9*y + 9*y) == 0)

True


### System of linear algebraic equations. Matrix recording.

<br>A = np.array([
<br>  [a11, a12, ... a1m],
<br>  [a21, a22, ... a2m],
<br>   ...  ...  ... ...
<br>  [an1, an2, ... anm]
<br>])

<br>x = np.array([
<br>    [x1],
<br>    [x2],
<br>    ...
<br>    [xm]
<br>])

<br>b = np.array([
<br>    [b1],
<br>    [b2],
<br>    ...
<br>    [bn]
<br>])

<br># Ax = b:
<br>Ax = np.array([
<br>    [a11*x1 + a12*x2 + ... + a1m*xm],
<br>    [a21*x1 + a22*x2 + ... + a2m*xm],
<br>               ...
<br>    [an1*x1 + an2*x2 + ... + anm*xm]          
<br>])

In [ ]:
v1 = np.array([1, 2])
v2 = np.array([2, 4])
print(2*v1 + (-1)*v2)

[0 0]


In [ ]:
v1 = np.array([1, 2, 3, 1])
v2 = np.array([4, 5, 6, 1])
v3 = np.array([7, 8, 9, 1])

w1v1 + w2v2 + w3v3 = 0
<br>
<br>w1*[1,2,3,1] + w2*[4,5,6,1] + w3*[7,8,9,1] = [0,0,0,0]
<br>
<br>w1 + 4*w2 + 7*w3 = 0
<br>2*w1 + 5*w2 + 8*w3 = 0
<br>3*w1 + 6*w2 + 9*w3 = 0
<br>w1 + w2 + w3 = 0
<br>
<br>w1 + 4*w2 + 7*w3 = 0
<br>w1 + w2 + w3 = 0
<br>w1 + w2 + w3 = 0
<br>w1 + w2 + w3 = 0
<br>
<br>w1 + 4*w2 + 7*w3 = 0
<br>w1 + w2 + w3 = 0
<br>
<br>w1 + w2 + w3 = 0
<br>3w2 + 6w3 = 0
<br>
<br>w1 + w2 + w3 = 0
<br>w2 + 2w3 = 0
<br>
<br>w1 = 1
<br>w2 = -2
<br>w3 = 1
<br>
<br>A = [
<br>  [1, 4, 7],
<br>  [2, 5, 8],
<br>  [3, 6, 9],
<br>  [1, 1, 1]
<br>]
<br>
<br>w = [w1, w2, w3]
<br>
<br>A = [
<br>  [1, 1, 1],
<br>  [0, 1, 2],
<br>  [0, 0, 0],
<br>  [0, 0, 0]
<br>]

### Rank

In [ ]:
V2 = np.array([
    [1, 1, 1],
    [0, 1, 2],
    [0, 0, 0],
    [0, 0, 0]          
])

V3 = np.array([
    [1, 1, 1],
    [0, 1, 2],
    [0, 0, 1],
    [0, 0, 0]          
])

### Python solution

In [ ]:
import numpy as np
v1 = np.array([1, 2, 3, 1])
v2 = np.array([4, 5, 6, 1])
v3 = np.array([7, 8, 9, 1])

A = np.array([v1, v2, v3]).T

print(A)
print('------')
print(np.linalg.matrix_rank(A))

[[1 4 7]
 [2 5 8]
 [3 6 9]
 [1 1 1]]
------
2


In [ ]:
import numpy as np
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])

A = np.array([v1, v2, v3]).T
print(A)
print('-----')
print(np.linalg.matrix_rank(A))

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6 10]
 [ 1  1  1]]
-----
3


### TASK 9.6

In [ ]:
A = np.array([
    [1, 2, 0],
    [4, 5, 0],
    [7, 8, 0]
])

print(np.linalg.matrix_rank(A))
print(np.linalg.det(A))

2
0.0


### TASK 9.7

In [ ]:
A = np.array([
    [1, 0, 3, 5],
    [0, 4, 5, 5],
    [0, 0, 0, 0],
    [0, 0, 0, 0]            
])

B = np.array([
    [1, 0, 3, 5],
    [0, 4, 5, 5],
    [0, 0, 0, 4],
    [0, 0, 0, 0]            
])

print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

2
3


### TASK 9.8

In [ ]:
a = np.array([4, 1, 0])
b = np.array([-1, 4, 0])
c = np.array([0, 0, 1])

A = np.array([a, b, c]).T
print(A)
print('------')
print(np.dot(a, b))
print(np.dot(a, c))
print(np.dot(b, c))
print('------')
print(np.linalg.matrix_rank(A))

[[ 4 -1  0]
 [ 1  4  0]
 [ 0  0  1]]
------
0
0
0
------
3
