### NUMPY

In [17]:
import numpy as np

a = np.int8(127)
b = np.uint8(255)

print(a)
print(type(a))
np.iinfo(a)
print(b)

127
<class 'numpy.int8'>
255


### Float

In [19]:
print(np.finfo(np.float16))
print(np.finfo(np.float32))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------



### Additional types

In [20]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


### Arrays

In [24]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr

array([ 1,  5,  2,  9, 10])

In [27]:
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int32


In [28]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [32]:
arr = np.float64(arr)
arr.dtype

dtype('float64')

### Array properties

In [37]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_array = np.array([
    [12, 45, 78],
    [34, 56, 13],
    [12, 98, 76]
], dtype=np.int16)

print(arr.ndim)
print(nd_array.ndim)
print(arr.size)
print(nd_array.size)
print(arr.shape)
print(nd_array.shape)
print(arr.itemsize)
print(nd_array.itemsize)

1
2
5
9
(5,)
(3, 3)
1
2


### Filling new arrays

In [38]:
zeros_1d = np.zeros(5)
zeros_3d = np.zeros((5,4,3), dtype=np.float32)

print(zeros_1d)
print(zeros_3d)

[0. 0. 0. 0. 0.]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [47]:
arr1 = np.arange(5)
arr2 = np.arange(2.5, 5)
arr3 = np.arange(2.5, 5, 0.5)
arr4 = np.arange(2.5, 5, 0.5, dtype=np.float16)
arr5 = np.linspace(1, 2, 10)
arr6 = np.linspace(1,2,10, endpoint=False)
arr7, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(step)

[0 1 2 3 4]
[2.5 3.5 4.5]
[2.5 3.  3.5 4.  4.5]
[2.5 3.  3.5 4.  4.5]
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
0.1111111111111111


### Working with arrays

In [55]:
arr = np.arange(8)
print(arr)

[0 1 2 3 4 5 6 7]


In [54]:
arr.shape = (2, 4)
print(arr)

[[0 1 2 3]
 [4 5 6 7]]


In [57]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new2 = arr.reshape((2, 4), order='F')

print(arr)
print(arr_new)
print(arr_new2)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 2 4 6]
 [1 3 5 7]]


In [59]:
arr = np.arange(8)
arr.shape = (2, 4)
arr_trans = arr.transpose()

print(arr)
print(arr_trans)

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


### Indexes and slices in arrays

In [63]:
arr = np.linspace(1, 2, 6)

print(arr)
print(arr[2])
print(arr[2:4])
print(arr[::-1])

[1.  1.2 1.4 1.6 1.8 2. ]
1.4
[1.4 1.6]
[2.  1.8 1.6 1.4 1.2 1. ]


In [71]:
nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3,4)

print(nd_array)
print()
print(nd_array[1][2])
print()
print(nd_array[1, 2])
print()
print(nd_array[:2,2])
print()
print(nd_array[1:,2:4])
print()
print(nd_array[:, 2:4])

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

3.0

3.0

[1. 3.]

[[3.  3.5]
 [5.  5.5]]

[[1.  1.5]
 [3.  3.5]
 [5.  5.5]]


### Sort 1d arrays

In [73]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)

print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [74]:
arr = np.array([23,12,45,12,23,4,15,3])

print(arr.sort())
print(arr)

None
[ 3  4 12 12 15 23 23 45]


### Working with missing data

In [83]:
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)

print(roots)
print()
print(np.isnan(roots))
print()
print(roots[np.isnan(roots)])
print()

roots[np.isnan(roots)] = 0
print(roots)

[2.         3.                nan 1.73205081]

[False False  True False]

[nan]

[2.         3.         0.         1.73205081]


C:\Users\Алексей\AppData\Local\Temp\ipykernel_6928\2561038302.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


### Vectors in Numpy

In [84]:
import numpy as np

# Sum
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [85]:
# Multiply
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [88]:
# Multiply by number
vec = np.arange(5)

vec**2

array([ 0,  1,  4,  9, 16])

In [89]:
# Comparison
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 > vec2

array([False, False,  True, False])

In [90]:
# Comparison with number
vec = np.array([14, 15, 9, 26, 53, 5, 89])

vec <= 26

array([ True,  True,  True,  True, False,  True, False])

### Advanced working with vectors

In [91]:
# Length of the vector
vec = np.array([3, 4])
length = np.sqrt(np.sum(vec**2))

print(length)

5.0


In [92]:
# Length of the vector
vec = np.array([3, 4])
length = np.linalg.norm(vec)

print(length)

5.0


In [93]:
# Distance of the vectors
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)

print(distance)

12.206555615733702


In [95]:
# Scalar product
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1*vec2)

scalar_product2 = np.dot(vec1, vec2)

print(scalar_product)
print(scalar_product2)

250.0
250.0


In [96]:
x = np.array([25, 0])
y = np.array([0, 10])
print(np.dot(x, y))

0


### Base statistic functions

In [101]:
vec = np.array([2, 7, 18, 28, 18, 1, 8, 4])

print(vec.min())
print(vec.max())
print(vec.mean())

1
28
10.75


### The random numbers

In [105]:
import numpy as np

# Generation using 'random.rand()'
rand_num = np.random.rand()
rand_arr = np.random.rand(5)
rand_arr_2d = np.random.rand(2, 3)

print(rand_num)
print(rand_num*100)
print(rand_arr)
print(rand_arr_2d)

0.5371049786560099
53.71049786560099
[0.38352315 0.70060996 0.93039367 0.09313949 0.01099814]
[[0.03362531 0.0228232  0.03061642]
 [0.57387903 0.24177392 0.76263385]]


In [106]:
# Generation using 'random.sample()'
shape = (2, 3)
random_arr = np.random.sample(shape)

print(random_arr)

[[0.76575057 0.08797571 0.83036378]
 [0.71327705 0.36173965 0.51862922]]


In [110]:
# Generation using 'random.uniform()'
random_1 = np.random.uniform()
random_2 = np.random.uniform(-30, 50)
random_3 = np.random.uniform(0.5, 0.75, size=5)
random_4 = np.random.uniform(-1000, 500, size=(2, 3))

print(random_1)
print(random_2)
print(random_3)
print(random_4)

0.22194350017320752
40.93545812017523
[0.69395942 0.72528501 0.52445405 0.61337888 0.6244678 ]
[[ 195.89765158 -168.32287736  -55.89886134]
 [-266.82207551 -879.11552854 -114.9040928 ]]


In [113]:
# Generation using 'random.randint()'
random_1 = np.random.randint(4, size=(2,3))
random_2 = np.random.randint(6, 12, size=(3,3))

print(random_1)
print(random_2)

[[2 0 1]
 [2 2 1]]
[[ 9 11  7]
 [ 8 10  8]
 [ 8  6  9]]


### The sample generation

In [116]:
# Shuffling arrays with 'shuffle'
arr = np.arange(6)
print(arr)

np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5]
[1 5 4 0 3 2]


In [119]:
# Shuffling arrays with 'permutation'
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)

print(playlist)
print(shuffled)
print(np.random.permutation(10))

['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']
['Deep Purple' 'Pink Floyd' 'ACDC' 'The Beatles']
[6 7 4 0 8 9 1 3 2 5]


In [121]:
# Random objects with 'random.choice()'
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=2, replace=False)
choice_2  = np.random.choice([1, 2, 3, 4, 5, 6], size=10)

print(choice)
print(choice_2)

['Kate' 'John']
[3 4 5 4 4 5 4 3 6 5]


In [125]:
# The seed
np.random.seed(23)
rand_1 = np.random.randint(10, size=(3,4))
np.random.seed(23)
rand_2 = np.random.randint(10, size=(3,4))

print(rand_1)
print(rand_2)

[[3 6 8 9]
 [6 8 7 9]
 [3 6 1 2]]
[[3 6 8 9]
 [6 8 7 9]
 [3 6 1 2]]
